- name: ‘Installing webserver Software’
  apt: name= {{item}}
  with_items:
  - apache2 
- name: ‘Enabling proxy module’
  apache2_module: name=proxy_http
- name: ‘adding proxy configuration’
  template: src=../files/proxy.conf dest=/etc/apache2/conf-available owner=root mode=0644 
  notify: 
  - enable-proxy-config 
